apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kahoot-clone
data:
  NODE_ENV: "production"
  
  # Gateway
  GATEWAY_PORT: "3000"
  
  # Service URLs (internal Kubernetes service names)
  AUTH_SERVICE_URL: "http://auth-service:3001"
  QUIZ_SERVICE_URL: "http://quiz-service:3002"
  GAME_SERVICE_URL: "http://game-service:3003"
  USER_SERVICE_URL: "http://user-service:3004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3005"
  
  # Service Ports
  AUTH_PORT: "3001"
  QUIZ_PORT: "3002"
  GAME_PORT: "3003"
  USER_PORT: "3004"
  ANALYTICS_PORT: "3005"
  FRONTEND_PORT: "3006"
  
  # CORS
  CORS_ORIGIN: "*"
  
  # Frontend Configuration (for browser access)
  # Using worker node IP where gateway service is accessible
  REACT_APP_API_URL: "http://44.198.175.214:30000"
  REACT_APP_SOCKET_URL: "http://44.198.175.214:30004"
  
  # AWS S3 Configuration (for avatar uploads)
  AWS_REGION: "us-east-1"
  S3_AVATAR_BUCKET: "kahoot-clone-user-avatars-802346121373"
  
  # JWT
  JWT_EXPIRES_IN: "7d"
  
  # Email Server (non-sensitive)
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  
  # OTP
  OTP_EXPIRES_IN: "10"
